name: Android CI/CD (Test Build)

on:
  push:
    branches:
      - master
      - develop
      - feature/*
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build APK and AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create gradle.properties
        run: |
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          echo "kotlin.code.style=official" >> gradle.properties
          echo "android.nonTransitiveRClass=true" >> gradle.properties
          echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> gradle.properties

      - name: Setup Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Full Gradle Cache Cleanup
        run: |
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/wrapper/
          rm -rf ~/.gradle/kotlin-dsl/

      - name: Force Gradle Dependencies Refresh
        run: ./gradlew --refresh-dependencies

      - name: Build APK (Debug)
        run: ./gradlew assembleDevDebug

      - name: Build AAB (Release)
        run: ./gradlew bundleProdRelease

      - name: Upload APK/AAB as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: app/build/outputs/**/*.apk

      - name: Send APK to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          APK_PATH=$(find app/build/outputs/apk/dev/debug -name "*.apk" | head -n 1)
          curl -F chat_id="$TELEGRAM_CHAT_ID" \
               -F document="@$APK_PATH" \
               -F caption="✅ Новый тестовый билд доступен!" \
               "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument"
